    - name: Create a directory on root
      become: yes
      become_user: root
      file:
        path: "{{ local_home_dir }}/proyectos_git"
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        state: directory
    - name: Clone the Notable github repo locally
      become_user: "{{ local_user }}"
      git:
        repo: 'https://github.com/notable/notable.git'
        dest: "{{ local_home_dir }}/proyectos_git"
        clone: yes
        recursive: yes
        force: yes
        version: master
      become: yes
      #become_user: root
      
    - name: tarea posinstalacion 1     # copiar la configuracion de nginx
      template:
       src: templates/minginx.conf
       dest: /etc/nginx/conf.d/minginx.conf
       mode: '0400'
      notify: nginx_reconfigurado
      
    #- name: tarea posinstalacion 2     # clonar el web
    #  git:
    #    repo: 'https://github.com/damopi95/webEjemploAnsible'
    #    dest: "{{ nginx_web_path }}"
    
    - name: tarea posinstalacion 2     # clonar el web
      git:
        repo: 'https://damopi95:{{password_github}}@github.com/damopi95/webEjemploAnsible_private'
        dest: "{{ nginx_web_path }}"